name: Build EXE

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install
      run: |
        pip install flask pillow pyinstaller

    - name: Build exe
      run: |
        pyinstaller --onefile --noconsole app.py

    - name: Zip
      run: |
        powershell Compress-Archive -Path dist/app.exe -DestinationPath app.zip

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: app.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
  contents: write
